### PR TITLE
Fixed bug where getNpmPaths fails when process.argv[1] is not provided

### PR DESCRIPTION
**Pull request by zhuochen83**

### CODE REVIEW

**Comment by sindresorhus** [comment]
> fails when process.argv[1] is not provided

When would that ever happen?

**Comment by MarshallOfSound** [comment]
@sindresorhus This module is used by https://github.com/resin-io/nplugm to scan `node_modules` directories.  As such it is invoked from inside node where the process might not have a `process.argv[1]` set to anything.

In this case `path.dirname` throws errors as `undefined` is not a path it can handle.

**Comment by MarshallOfSound** [comment]
See https://github.com/resin-io/nplugm/blob/master/lib/resolver.coffee#L43

**Comment by SBoudrias** [comment]
I think that makes sense. If yeoman-environment is used outside a bin script, it could cause issues.

**Pull request merged**
