### PR TITLE
use `path-exists` as `fs.exists` is being deprecated

### PR DESCRIPTION
**Pull request by arthurvr**
Ref https://github.com/sindresorhus/path-exists

### CODE REVIEW

**Comment by arthurvr** [comment]
The failing tests on node 0.10 are mainly because of https://github.com/yeoman/environment/issues/4 I think. It timed out.

**Comment by addyosmani** [comment]
change lgtm. Will hold off on merging until we know the cause of failing tests.

**Comment by SBoudrias** [comment]
Yeah, I tried re-running the test but Travis is having issues.

Let's make sure this is passing before we go on. If we hit timeouts, then it might mean `path-exists` it not as performant as `fs.exists` - and obviously that would be a huge issue for us.

**Comment by sindresorhus** [comment]
> If we hit timeouts, then it might mean path-exists it not as performant as fs.exists - and obviously that would be a huge issue for us.

It has the same performance. Even if it were a lot slower it would not matter as it's only used for two checks.

But how `existsSync` sync is used before this PR is exactly why it was deprecated. This introduces a race condition between the `fs` calls (see the `path-exists` readme). The right way is to just try to do it and handle the `ENOENT` error.

**Comment by SBoudrias** [comment]
Ah thanks, didn't look into the actual CR code before.

So yeah, these should just be fixed to handle the error, not switching to path-exists.

**Pull request closed without merging**
