### PR TITLE
Store package info when performing a lookup.

### PR DESCRIPTION
**Pull request by mshima**
With packagePath will be possible to get the generator's package.json.

### CODE REVIEW

**Comment by mshima** [comment]
Closing, trying to improve this.
Will reopen latter.

**Comment by mshima** [comment]
Added another commit.

**Comment by SBoudrias** [comment]
In which case will `packagePath` be defined when registering? It seems like it can only be done manually currently?

**Comment by SBoudrias** [comment]
I see this was added in your other PR. This code change looks fine by me, thanks!

**Pull request merged**
